<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>PiercingWailSound</AssemblyName>
    <GameDir>C:\Program Files (x86)\Steam\steamapps\common\Slay the Spire 2</GameDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>$(GameDir)\data_sts2_windows_x86_64\sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
	<Reference Include="0Harmony">
		<HintPath>$(GameDir)\data_sts2_windows_x86_64\0Harmony.dll</HintPath>
		<Private>false</Private>
	</Reference>
    <PackageReference Include="Alchyr.Sts2.BaseLib" Version="*" />
    <PackageReference Include="GodotSharp" Version="4.4.0" />
  </ItemGroup>

  <!-- Auto-copy DLL to mods folder on every build -->
  <Target Name="CopyDll" AfterTargets="Build">
    <Copy
      SourceFiles="$(OutputPath)$(AssemblyName).dll"
      DestinationFolder="$(GameDir)\mods\$(AssemblyName)" />
  </Target>
</Project>